org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
neo_version=21.1.251

mod_id=wtfim
mod_name=What the Fuck Is Matcha?
mod_license=All Rights Reserved
mod_version=0.1.0-alpha
mod_group_id=dev.wtfim
